### ISSUE TITLE
Initial testing on feat/voice_pairing branch

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/skill-ovos-setup#20]
Initial thoughts and tests.
On boot, pairing comes up with 3 choices and audio sounds good.
My choice "Run locally"
Once again the voice sounds good with the validation
First bug*
  * When mycroft asks  `Did i understand correctly you want to use the offline backend` it does not give time to answer.  When it re-asks, works fine.
  * I answer `yes` and then the real error occurs
    * Mycroft says `An error occurred while processing a request in Pairing Skill`
This is the logs
```
2022-09-18 14:59:02.023 - OVOS - ovos_config.config:_on_file_change:269 - INFO - /home/mycroft/.config/mycroft/mycroft.conf changed on disk, reloading!
2022-09-18 14:59:02.046 - OVOS - ovos_config.models:load_local:136 - ERROR - Error loading configuration '/home/mycroft/.config/mycroft/mycroft.conf'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ovos_config/models.py", line 131, in load_local
    config = load_commented_json(path)
  File "/usr/lib/python3.10/site-packages/ovos_utils/json_helper.py", line 129, in load_commented_json
    return json.loads(uncomment_json(contents))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-18 14:59:02.269 - OVOS - mycroft.audio.service:execute_tts:157 - INFO - Speak: An error occurred while processing a request in Pairing Skill
```

I am assuming that it is not writing the file correctly? But it does add the `server` section at the end.
```
cat .config/mycroft/mycroft.conf 
{
  "tts": {
    "module": "ovos-tts-plugin-marytts",
    "neon-tts-plugin-larynx-server": {
      "host": "http://tts.neon.ai",
      "voice": "mary_ann",
      "vocoder": "hifi_gan/vctk_small"
    },
    "ovos-tts-plugin-marytts": {
      "url": "http://ziggy.ziggyhome:59125",
      "voice": "en_US/vctk_low#s5"
    }
  },
  "system_unit": "imperial",
  "location": {
    "city": {
      "code": "Orchard City",
      "name": "Hotchkiss",
      "state": {
        "code": "CO",
        "name": "Colorado",
        "country": {
          "code": "US",
          "name": "United States"
        }
      }
    },
    "coordinate": {
      "latitude": 38.8455879,
      "longitude": -107.7932359
    },
    "timezone": {
      "code": "America/Denver",
      "name": "Moutain Standard Time",
      "dstOffset": 3600000,
      "offset": -21600000
    }
  },
  "opt_in": true,
  "Audio": {
    "backends": {
      "OCP": {
        "type": "ovos_common_play",
        "dbus_type": "system",
        "manage_external_players": true,
        "active": true,
        "youtube_backend": "youtube-dl",
        "ydl_backend": "auto"
      },
      "vlc": {
        "type": "ovos_vlc",
        "active": true
      },
      "simple": {
        "type": "ovos_audio_simple",
        "active": true
      }
    },
    "default-backend": "OCP"
  },
  "gui": {
    "extension": "smartspeaker",
    "idle_display_skill": "skill-ovos-homescreen.builderjer"
  },
  "date_format": "MDY-us",
  "VAD": {
    "silence_method": "vad_and_ratio",
    "speech_seconds": 0.1,
    "silence_seconds": 0.5,
    "before_seconds": 0.5,
    "min_seconds": 1,
    "max_current_ratio_threshold": 2,
    "initial_energy_threshold": 1000.0,
    "module": "ovos-vad-plugin-webrtcvad",
    "ovos-vad-plugin-silero": {
      "threshold": 0.2
    },
    "ovos-vad-plugin-webrtcvad": {
      "vad_mode": 3
    }
  },
  "padatious": {
    "intent_cache": "~/.local/share/mycroft/intent_cache",
    "train_delay": 4,
    "single_thread": false,
    "regex_only": false,
    "fuzz": true
  },
  "server": {
    "disabled": true
  }
```

**Comment by builderjer** [comment]
This is using only voice

**Comment by builderjer** [comment]
Same thing when trying to pair with mycroft

**Comment by builderjer** [comment]
I think it is not writing it identity2.json file correct.
```
cat ~/.config/mycroft/identity/identity2.json
{"uuid":
```
nothing after the `uuid`

**Comment by builderjer** [comment]
Updated to latest everything, setup, backend, selene-api and now have this error.
```
2022-09-18 21:11:20.106 - OVOS - ovos_config.config:_on_file_change:269 - INFO - /home/mycroft/.config/mycroft/mycroft.conf changed on disk, reloading!
2022-09-18 21:11:20.165 - OVOS - mycroft.identity:_update:95 - DEBUG - Updaing identity
2022-09-18 21:11:20.208 - OVOS - ovos_config.models:load_local:134 - DEBUG - Configuration /home/mycroft/.config/mycroft/mycroft.conf loaded
2022-09-18 21:11:20.606 - OVOS - ovos_workshop.skills.ovos:_on_event_error:220 - ERROR - Object of type UUID is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/home/mycroft/.local/share/mycroft/skills/skill-ovos-setup.openvoiceos/__init__.py", line 541, in handle_backend_confirmation_event
    self.handle_no_backend_selected(message)
  File "/home/mycroft/.local/share/mycroft/skills/skill-ovos-setup.openvoiceos/__init__.py", line 571, in handle_no_backend_selected
    self.setup.change_to_no_backend()
  File "/home/mycroft/.local/share/mycroft/skills/skill-ovos-setup.openvoiceos/__init__.py", line 173, in change_to_no_backend
    self.create_dummy_identity()
  File "/home/mycroft/.local/share/mycroft/skills/skill-ovos-setup.openvoiceos/__init__.py", line 183, in create_dummy_identity
    IdentityManager.save(login)
  File "/usr/lib/python3.10/site-packages/mycroft/identity/__init__.py", line 86, in save
    json.dump(IdentityManager.__identity.__dict__, f)
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
```

**Comment by JarbasAl** [comment]
closing as voice pairing is no longer available / needed
